version: '3'

services:
  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: node_app
    container_name: node_app
    restart: unless-stopped
    networks:
      - app-network

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - node_app
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email hackins@your_domain.com --agree-tos --no-eff-email --force-renewal -d your_domain.com  -d www.your_domain.com

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/hackins/node_js_demo/views/
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/hackins/node_js_demo/dhparam/
      o: bind

networks:
  app-network:
    driver: bridge